project:
  type: website
  output-dir: docs
website:
  title: "Responsi Alin-1 2023"
  sidebar:
    - text: Responsi
      contents: responsi-md/*
    - text: dokumen-lainnya
      contents:
        - Alin-Kuis-1-PG-2022.pdf


  navbar:
    right: 
      - icon: github
        href: https://github.com/carlesoctav/alin-1-asdos
      - icon: twitter
        href: https://twitter.com/carlesoctav



  comments:
    giscus:
      repo: carlesoctav/alin-1-asdos


format:
  html:
    theme: litera
    css: styles.css
    toc: true


