project:
  type: website
  output-dir: docs
website:
  title: "Responsi Alin-1 2023"
  sidebar:
    contents: responsi-md/*


  navbar:
    right: 
      - icon: github
        href: https://github.com/carlesoctav/alin-1-asdos
      - icon: twitter
        href: https://twitter.com/carlesoctav



format:
  html:
    theme: litera
    css: styles.css
    toc: true



